In [ ]:
##########################################################################
# Author: Steve Kuruvilla, Shrasth Kumar                                 #
# Description: Main Program                                              #
##########################################################################

import src.filter_dataset as filter_dataset

occurance_dataset = filter_dataset.load_and_filter_dataset('.\\datasets\\OCCURRENCE_PUBLIC.csv', 5000, 'Fre')
injuries_dataset = filter_dataset.load_and_filter_dataset('.\\datasets\\INJURIES_PUBLIC.csv', 10)
train_dataset = filter_dataset.load_and_filter_dataset('.\\datasets\\TRAIN_PUBLIC.csv', 1000, 'Fre')
components_dataset = filter_dataset.load_and_filter_dataset('.\\datasets\\COMPONENTS_PUBLIC.csv', 1000, 'Fre')

occurance_dataset.to_csv('.\\datasets\\filtered\\OCCURRENCE_PUBLIC.csv', index=False)
injuries_dataset.to_csv('.\\datasets\\filtered\\INJURIES_PUBLIC.csv', index=False)
train_dataset.to_csv('.\\datasets\\filtered\\TRAIN_PUBLIC.csv', index=False)
components_dataset.to_csv('.\\datasets\\filtered\\COMPONENTS_PUBLIC.csv', index=False)

import pandas as pd

df = pd.read_csv('.\\datasets\\filtered\\INJURIES_PUBLIC.csv')

# Define categories
categories = {
    "Employee Injuries": ["Offtrain_EmployeeFatal", "Offtrain_EmployeeSerious", "Offtrain_EmployeeMinor"],
    "RS Passenger Injuries": ["Offtrain_RS_PassengerFatal", "Offtrain_RS_PassengerSerious", "Offtrain_RS_PassengerMinor"],
    "Vehicle Operator Injuries": ["Offtrain_VehicleOperatorFatal", "Offtrain_VehicleOperatorSerious", "Offtrain_VehicleOperatorMinor"],
    "Vehicle Passenger Injuries": ["Offtrain_VehiclePassengerFatal", "Offtrain_VehiclePassengerSerious", "Offtrain_VehiclePassengerMinor"],
    "Pedestrian Injuries": ["Offtrain_PedestrianFatal", "Offtrain_PedestrianSerious", "Offtrain_PedestrianMinor"],
    "Trespasser Injuries": ["Offtrain_TrespasserFatal", "Offtrain_TrespasserSerious", "Offtrain_TrespasserMinor"],
}

# Group and aggregate
summary = {}
total_fatalities = 0
total_serious = 0
total_minor = 0

for category, cols in categories.items():
    fatalities = df[cols[0]].sum()
    serious_injuries = df[cols[1]].sum()
    minor_injuries = df[cols[2]].sum()
    total = fatalities + serious_injuries + minor_injuries
    
    # Update total counts
    total_fatalities += fatalities
    total_serious += serious_injuries
    total_minor += minor_injuries

    summary[category] = {
        "Fatalities": fatalities,
        "Serious Injuries": serious_injuries,
        "Minor Injuries": minor_injuries,
        "Total Cases": total,
    }

# Adding total row
summary["Total"] = {
    "Fatalities": total_fatalities,
    "Serious Injuries": total_serious,
    "Minor Injuries": total_minor,
    "Total Cases": total_fatalities + total_serious + total_minor,
}

# Convert to DataFrame
summary_df = pd.DataFrame.from_dict(summary, orient="index")

summary_df.head(30)

,Fatalities,Serious Injuries,Minor Injuries,Total Cases
Employee Injuries,122,130,1834,2086
RS Passenger Injuries,26,27,785,838
Vehicle Operator Injuries,1101,842,3299,5242
Vehicle Passenger Injuries,171,272,492,935
Pedestrian Injuries,305,135,113,553
Trespasser Injuries,2145,783,681,3609
Total,3870,2189,7204,13263

In [ ]:
import pandas as pd

df = pd.read_csv('.\\datasets\\filtered\\INJURIES_PUBLIC.csv')

# List of all injury columns
fatal_cols = [col for col in df.columns if "Fatal" in col]
serious_cols = [col for col in df.columns if "Serious" in col]
minor_cols = [col for col in df.columns if "Minor" in col]

# Calculate the totals for each row
df["Fatalities"] = df[fatal_cols].sum(axis=1)
df["Serious Injuries"] = df[serious_cols].sum(axis=1)
df["Minor Injuries"] = df[minor_cols].sum(axis=1)
df["Total Cases"] = df["Fatalities"] + df["Serious Injuries"] + df["Minor Injuries"]

# Select required columns and sort by Total Cases in descending order
result_df = df[["OccID", "OccNo", "Fatalities", "Serious Injuries", "Minor Injuries", "Total Cases"]] \
    .sort_values(by="Total Cases", ascending=False)

# Display results
result_df.head(30).columns

result_df

,OccID,OccNo,Fatalities,Serious Injuries,Minor Injuries,Total Cases
22604,31774,R86Q0406,0,0,194,194
22627,31751,R86C0490,46,0,142,188
13074,41702,R91H0026,0,8,134,142
13075,41702,R91H0026,0,8,134,142
14806,39945,R90H0627,0,0,98,98
1915,118407,R13D0054,94,0,0,94
18436,36158,R88T2166,0,0,84,84
1888,118587,R13T0192,12,20,40,72
16274,38429,R89V1867,0,0,72,72
1889,118587,R13T0192,12,20,40,72
4659,97421,R01E0009,2,0,68,70
25355,28850,R83Q1564,0,0,60,60
19802,34698,R85C0944,2,0,56,58
25269,28936,R83Q1575,0,0,56,56
24679,29573,R84T0319,0,0,56,56
25365,28840,R83M0651,0,0,52,52
18602,35974,R87W1381,0,0,36,36
3356,105398,R06T0158,0,0,34,34
26146,28047,R83T3075,0,0,30,30
14319,40444,R90H1230,0,0,30,30
15019,39719,R90Q0191,2,0,28,30
21264,33190,R87W0916,0,0,28,28
26161,28032,R83C1617,10,0,18,28
23255,31089,R85V0794,0,0,26,26
26291,27901,R83Q1400,0,0,26,26
16255,38449,R89T2914,0,0,24,24
25234,28972,R83M0660,0,0,24,24
25705,28497,R83V2101,0,0,24,24
3848,102413,R04W0143,0,2,20,22
23739,30577,R85Q0273,0,0,22,22